# Numpy <hr style = "border:3px solid rgba(19, 29, 225, 1)"></hr>

<b> Lance Patrick G. De la Peña</b>
<br> Computer Engineer </br>

In [2]:
import numpy as np

# 1D Array


In [3]:
my_array = [1,2,3]

In [6]:
type(my_array)

numpy.ndarray

In [ ]:
my_array= np.array([1,2,3])

In [7]:
np.shape(my_array)

(3,)

# 2D Array


In [8]:

my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.shape(my_array)

(2, 3)

In [16]:
trans_array = my_array.T
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
np.shape(trans_array)

(3, 2)

In [17]:
np.sum(trans_array, axis=0)

array([ 6, 15])

In [18]:
np.sum(trans_array, axis=1)

array([5, 7, 9])

# Measure of Central Tendency

In [21]:
resistance = np.array ([
    [10.6,9.1,9.3,9.8,10.5,10.4, 9.5,11,10.4,3,9.8],#Jaguar
    [10.1,11,9.1,20, 9.2,10.8,9.9,9.2,9.1,9.1,np.nan]#Panther
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [24]:
np.nanmean(resistance,axis=1)

array([ 9.4 , 10.75])